dist: precise
language: python

python:
  - "2.7"
  - "3.5"

branches:
  only:
    - master
    - beta
    - develop

env:
    - Drivers=True    # First in build mx because long duration
    - Algorithms=True 
    - AlgorithmsB=True
    - Default=True    # construction, io, objects, tools, optimize
    - Report=True      
    - ReportB=True
    - MPI=True        

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install gfortran libblas-dev liblapack-dev
  - sudo apt-get -qq install openmpi-bin openmpi-common openssh-client openssh-server libopenmpi1.3 libopenmpi-dbg libopenmpi-dev >/dev/null
  - sudo bash CI/install.sh # Only install texlive and extensions if we need them
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" #some tests require a display
  - sleep 3 # give xvfb some time to start

install:
  - travis_retry travis_wait pip install -r requirements.txt
  - pip install --global-option=build_ext --global-option="-I/usr/include/suitesparse" cvxpy cvxopt >/dev/null
  - pip install ipython mpi4py zmq coverage msgpack-python >/dev/null
  - pip install -e . >/dev/null
  
cache:
  pip: true
  timeout: 1000

#Script For default "test" stage
script:
  - cd test
  - travis_wait 50 python travisTests.py # Tests may take some time!
  - cd ..

jobs:
  include:
    - stage: deploy
      python: 3.5
      env: Drivers=False Algorithms=False AlgorithmsB=False Default=False Report=False ReportB=False MPI=False
      script: python CI/deploy

notifications:
    email:
        on_success: change
        on_failure: always

